### ISSUE TITLE
Feature request: BTC RPC Explorer

### ISSUE THREAD

**Issue by wanxewoj** [zhiverbox/armbian-userpatches#1]
It would be awesome if zHIVErbox shiped with [BTC RPC Explorer](https://github.com/janoside/btc-rpc-explorer) or at least an installer for it.

**Comment by zciendor** [comment]
Thanks for the hint about `btc-rpc-explorer`. It wasn't straightforward to build an installer for zHIVErbox, because the Nodejs package manager `npm` doesn't support Socks5 proxy protocol. Therefore we first had to add an intermediary HTTP proxy `polipo` to zHIVErbox, which forwards the traffic to the Tor Socks5 proxy and configure `npm` to always use `polipo`. 
The nice result is, that we have a generic solution now for all nodejs-based applications.

However, we didn't implement `btc-rpc-explorer` as a system service (daemon) which is running all the time, but as an on-demand application instead which is accessed via `SSH TCP Port Forwarding`. This way we don't add an additional attack vector to zHIVErbox by exposing `btc-rpc-explorer` to everybody.
